Repository package-operator/package-operator, pull requests merged in 2022-10, with the labels that each got.

#49 Introduce InTransition condition
  apis/core/v1alpha1/commonobjectset_types.go
  integration/objectset_test.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
Labels: lgtm, approved

#56 Implement objectsetdeployment controller
  cmd/package-operator-manager/main.go
  config/examples/nginx/nginx-v1.yaml
  config/examples/nginx/nginx-v2.yaml
  config/examples/nginx/nginx-v3-broken.yaml
  config/examples/nginx/nginx-v4.yaml
  config/examples/nginx/nginx-v5.yaml
  config/examples/nginx/nginx-v6.yaml
  config/examples/nginx/nginx-v7.yaml
  go.work.sum
  integration/objectsetdeployment_test.go
  internal/controllers/objectdeployments/adapter.go
  internal/controllers/objectdeployments/adapter_test.go
  internal/controllers/objectdeployments/archive_reconciler.go
  internal/controllers/objectdeployments/archive_reconciler_test.go
  internal/controllers/objectdeployments/hash_reconciler.go
  internal/controllers/objectdeployments/mocks.go
  internal/controllers/objectdeployments/new_revision_reconciler.go
  internal/controllers/objectdeployments/new_revision_reconciler_test.go
  internal/controllers/objectdeployments/objectdeployment_controller.go
  internal/controllers/objectdeployments/objectset_reconciler.go
  internal/controllers/objectdeployments/objectset_reconciler_test.go
  internal/utils/hash.go
  internal/utils/objectset.go
Labels: approved

#58 ObjectDeployment cleanup
  apis/core/v1alpha1/clusterobjectdeployment_types.go
  apis/core/v1alpha1/commonpackage_types.go
  apis/core/v1alpha1/objectdeployment_types.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  docs/api-reference.md
  go.mod
  go.sum
  go.work.sum
  integration/objectdeployment_test.go
  integration/objectset_test.go
  internal/controllers/objectdeployments/adapter_objectdeployment.go
  internal/controllers/objectdeployments/adapter_objectset.go
  internal/controllers/objectdeployments/adapter_objectsetlist.go
  internal/controllers/objectdeployments/archive_reconciler.go
  internal/controllers/objectdeployments/mocks_test.go
  internal/controllers/objectdeployments/new_revision_reconciler.go
  internal/controllers/objectdeployments/new_revision_reconciler_test.go
  internal/controllers/objectdeployments/objectdeployment_controller.go
  internal/controllers/objectdeployments/objectset_reconciler.go
Labels: lgtm, approved

#63 Remove dead code
  internal/controllers/objectdeployments/new_revision_reconciler.go
  internal/controllers/objectdeployments/new_revision_reconciler_test.go
Labels: lgtm, approved

#45 mtsre 677 hypershift connector
  apis/core/v1alpha1/clusterobjectsetphase_types.go
  apis/core/v1alpha1/objectsetphase_types.go
  cmd/remote-phase-manager/main.go
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/images/remote-phase-manager.Containerfile
  config/remote-phase-static-deployment/2-rbac-target-cluster.yaml
  config/remote-phase-static-deployment/2-rbac.yaml
  config/remote-phase-static-deployment/2-secret.yaml.tpl
  config/remote-phase-static-deployment/deployment.yaml.tpl
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  docs/api-reference.md
  integration/objectset_test.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objectsetphases/objectsetphase_controller_test.go
  magefile.go
Labels: needs-rebase, lgtm, approved

#70 Generate install yaml file
  install.yaml
  magefile.go
Labels: lgtm, approved

#75 Adding real Objects to SSS
  hack/hive/deployment-template.yaml
Labels: lgtm, approved
