Repository package-operator/package-operator, pull requests merged in 2023-08, with the labels that each got.

#339 Added shortnames to CRDs
  apis/core/v1alpha1/clusterobjectdeployment_types.go
  apis/core/v1alpha1/clusterobjectset_types.go
  apis/core/v1alpha1/clusterobjectsetphase_types.go
  apis/core/v1alpha1/clusterobjectslices_types.go
  apis/core/v1alpha1/clusterobjecttemplate_types.go
  apis/core/v1alpha1/clusterpackage_types.go
  apis/core/v1alpha1/objectdeployment_types.go
  apis/core/v1alpha1/objectset_types.go
  apis/core/v1alpha1/objectsetphase_types.go
  apis/core/v1alpha1/objectslices_types.go
  apis/core/v1alpha1/objecttemplate_types.go
  apis/core/v1alpha1/package_types.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_clusterobjectsets.yaml
  config/crds/package-operator.run_clusterobjectslices.yaml
  config/crds/package-operator.run_clusterobjecttemplates.yaml
  config/crds/package-operator.run_clusterpackages.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/crds/package-operator.run_objectsets.yaml
  config/crds/package-operator.run_objecttemplates.yaml
  config/crds/package-operator.run_packages.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsets.yaml
  config/static-deployment/1-package-operator.run_clusterobjectslices.yaml
  config/static-deployment/1-package-operator.run_clusterobjecttemplates.yaml
  config/static-deployment/1-package-operator.run_clusterpackages.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsets.yaml
  config/static-deployment/1-package-operator.run_objecttemplates.yaml
  config/static-deployment/1-package-operator.run_packages.yaml
  install.yaml
Labels: lgtm, approved

#348 [MTSRE-994] Add code generation to pre-commit
  .pre-commit-config.yaml
Labels: lgtm, approved

#353 .gitignore go.work.sum since it is autogenerated anyway
  .gitignore
  go.work
  go.work.sum
Labels: lgtm, approved

#329 Update dependencies that do not break controller-runtime
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  integration/package-operator/objecttemplate_test.go
  internal/cmd/client.go
  internal/controllers/phase_reconciler_test.go
  internal/ownerhandling/annotation.go
  internal/ownerhandling/annotation_test.go
  internal/packages/errors_test.go
  internal/packages/packagecontent/topackage.go
  internal/packages/packageloader/validate.go
  internal/utils/hash_test.go
Labels: lgtm, approved

#358 enable leader-election by default
  cmd/package-operator-manager/components/options.go
  cmd/package-operator-manager/components/options_test.go
Labels: lgtm, approved

#351 Report Collision Detection Errors into API
  internal/controllers/config.go
  internal/controllers/objectsetphases/objectsetphase_adapter.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objectsetphases/objectsetphase_controller_test.go
  internal/controllers/objectsets/adapter_objectset.go
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/objectsets/objectset_controller_test.go
  internal/controllers/phase_reconciler.go
  internal/controllers/phase_reconciler_test.go
Labels: lgtm, approved

#352 Enable Template helpers
  cmd/kubectl-package/buildcmd/testdata/.test-fixtures/namespace-scope/namespace.template.yaml
  cmd/kubectl-package/validatecmd/testdata/.test-fixtures/cluster-scope/deployment.yaml
  cmd/kubectl-package/validatecmd/testdata/.test-fixtures/namespace-scope/deployment.yaml
  cmd/kubectl-package/validatecmd/testdata/.test-fixtures/namespace-scope/namespace.template.yaml
  cmd/kubectl-package/validatecmd/testdata/_helpers.gotmpl
  cmd/kubectl-package/validatecmd/testdata/deployment.yaml.gotmpl
  config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/trusted-ca-bundle.ConfigMap.yaml
  config/packages/package-operator/.test-fixtures/no-config/trusted-ca-bundle.ConfigMap.yaml
  config/packages/test-stub/.test-fixtures/namespace-scope/namespace.template.yaml
  integration/kubectl-package/testdata/packages/invalid/missing_lock_file/.test-fixtures/namespace-scope/namespace.template.yaml
  integration/kubectl-package/testdata/packages/valid/with_config/.test-fixtures/namespace-scope/namespace.template.yaml
  integration/kubectl-package/testdata/packages/valid/without_config/.test-fixtures/namespace-scope/namespace.template.yaml
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/package_files_template_transformer.go
  internal/packages/packageloader/testdata/_helpers.gotmpl
  internal/packages/packageloader/testdata/deployment.yml.gotmpl
  internal/packages/packageloader/testdata/whateverotherfile.gotmpl
  internal/packages/packageloader/validate.go
  internal/packages/packageloader/validatefull.go
Labels: lgtm, approved

#360 Fix remote ObjectSetPhase stuck in transition
  internal/controllers/objectsets/objectsetphases_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler_test.go
Labels: lgtm, approved

#355 Fix unittest not reporting on stdout
  cmd/package-operator-manager/bootstrap/bootstrap_test.go
  magefile.go
Labels: lgtm, approved

#364 Set hypershift isolation label
  config/packages/remote-phase/.test-fixtures/namespace-scope/package-operator-remote-phase-manager.Deployment.yaml
  config/packages/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl
Labels: lgtm, approved

#367 Fix upgrade loop on error
  cmd/package-operator-manager/bootstrap/init.go
  cmd/package-operator-manager/bootstrap/init_test.go
  internal/packages/packageimport/registry_test.go
Labels: approved

#354 MTSRE-1379 fix duplicate CRDs in self-bootstrap-job
  .gitignore
  cmd/package-operator-manager/bootstrap/bootstrap.go
  cmd/package-operator-manager/bootstrap/bootstrap_test.go
  cmd/package-operator-manager/bootstrap/fix.go
  cmd/package-operator-manager/bootstrap/fix/1.7.0_crd-pluralization.go
  cmd/package-operator-manager/bootstrap/fix/1.7.0_crd-pluralization_test.go
  cmd/package-operator-manager/bootstrap/fix/scheme_test.go
  cmd/package-operator-manager/bootstrap/fix/types.go
  cmd/package-operator-manager/bootstrap/fix_test.go
Labels: lgtm, approved

#369 Reenable dependabot, kill sonar, upload all files to codecov
  .github/dependabot.yml
  .github/workflows/sonar.yaml
  .github/workflows/testing.yaml
  .github/workflows/update.yaml
  sonar-project.properties
Labels: lgtm, approved

#368 Update the things
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: approved

#402 Update mage deps
  magefile.go
Labels: lgtm, approved

#409 Add logr to context of manager
  cmd/package-operator-manager/main.go
Labels: lgtm, approved, ¯\_(ツ)_/¯

#427 make (default)ImageOrg in magefile truly configurable
  config/self-bootstrap-job.yaml.tpl
  magefile.go
Labels: lgtm, approved

#430 retroactively apply PR review suggestion from @kostola
  magefile.go
Labels: lgtm, approved

#411 Add CEL probe
  apis/core/v1alpha1/commonobjectset_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_clusterobjectsets.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/crds/package-operator.run_objectsets.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsets.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsets.yaml
  docs/api-reference.md
  go.mod
  install.yaml
  integration/package-operator/objectdeployment_test.go
  internal/controllers/objectdeployments/new_revision_reconciler.go
  internal/controllers/objectdeployments/new_revision_reconciler_test.go
  internal/probing/cel.go
  internal/probing/cel_test.go
  internal/probing/parse.go
  internal/probing/parse_test.go
  magefile.go
Labels: lgtm, approved

#432 Revert "Add teardown job"
  cmd/package-operator-manager/bootstrap/init.go
  cmd/package-operator-manager/components/options.go
  cmd/package-operator-manager/main.go
  cmd/package-operator-manager/teardown/teardown.go
  cmd/package-operator-manager/teardown/teardown_test.go
  integration/package-operator/000_upgrade_test.go
  integration/package-operator/environment.go
  integration/package-operator/hypershift_test.go
  internal/controllers/packages/package_controller.go
  internal/controllers/packages/package_controller_test.go
  internal/utils/wait.go
  internal/utils/wait_test.go
Labels: do-not-merge/hold

#408 [MTSRE-1432] Prevent orphaned objects from being deleted
  integration/package-operator/hypershift_test.go
  integration/package-operator/objectset_test.go
  internal/controllers/objectsetphases/objectsetphase_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
Labels: lgtm, approved

#428 MTSRE-1454 fix HTTP(S) proxy configuration coming from in-cluster objects
  cmd/package-operator-manager/bootstrap/bootstrap.go
  cmd/package-operator-manager/bootstrap/proxy/proxy.go
  cmd/package-operator-manager/bootstrap/proxy/proxy_test.go
  go.mod
Labels: lgtm, approved
