Repository package-operator/package-operator, pull requests merged in 2023-04, with the labels that each got.

#250 Update dependencies
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved

#256 Support jsonpath spec for ObjectTemplate sources
  go.work.sum
  internal/controllers/objecttemplate/template_reconciler.go
  internal/controllers/objecttemplate/template_reconciler_test.go
Labels: lgtm, approved

#244 Basic monitoring
  apis/core/v1alpha1/clusterobjectdeployment_types.go
  apis/core/v1alpha1/commonpackage_types.go
  apis/core/v1alpha1/objectdeployment_types.go
  cmd/package-operator-manager/components/package.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterpackages.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_packages.yaml
  config/grafana-dashboard.json
  config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl
  config/service-monitor.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterpackages.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_packages.yaml
  config/static-deployment/deployment.yaml.tpl
  docs/api-reference.md
  install.yaml
  internal/adapters/objectdeployment.go
  internal/adapters/package.go
  internal/controllers/objectdeployments/adapters.go
  internal/controllers/objectdeployments/mocks_test.go
  internal/controllers/objectdeployments/objectset_reconciler.go
  internal/controllers/objectdeployments/objectset_reconciler_test.go
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/packages/object_deployment_status_reconciler.go
  internal/controllers/packages/package_controller.go
  internal/controllers/packages/unpack_reconciler.go
  internal/controllers/packages/unpack_reconciler_test.go
  internal/controllers/phase_reconciler.go
  internal/metrics/recorder.go
  internal/metrics/recorder_test.go
  magefile.go
Labels: approved

#263 Wrap preflight violations in SourceError
  internal/controllers/objecttemplate/template_reconciler.go
  magefile.go
Labels: lgtm, approved

#264 Simplify Self Bootstrap Job
  cmd/package-operator-manager/bootstrap/bootstrap.go
  cmd/package-operator-manager/bootstrap/init.go
  cmd/package-operator-manager/bootstrap/init_test.go
  cmd/package-operator-manager/components/options.go
  cmd/remote-phase-manager/main.go
  config/self-bootstrap-job.yaml.tpl
Labels: lgtm, approved

#270 Add ajpantuso to OWNERS
  OWNERS
Labels: lgtm, approved

#268 [MTSRE-1142] fix: apply backoff when external objects not found
  internal/controllers/config.go
  internal/controllers/errors.go
  internal/controllers/errors_test.go
  internal/controllers/objectsetphases/objectsetphase_reconciler.go
  internal/controllers/objectsetphases/objectsetphase_reconciler_test.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler_test.go
  internal/controllers/options.go
  internal/controllers/packages/unpack_reconciler.go
  internal/controllers/packages/unpack_reconciler_test.go
  internal/controllers/phase_reconciler.go
Labels: lgtm, approved, ok-to-test

#273 Add b64decMap function to template engine to allow the bulk-decode of…
  internal/transform/transformfiles_funcs.go
  internal/transform/transformfiles_funcs_test.go
Labels: lgtm, approved
