Repository package-operator/package-operator, pull requests merged in 2023-02, with the labels that each got.

#149 Update deps in magefile and CI
  .github/workflows/release.yaml
  .github/workflows/testing.yaml
  magefile.go
Labels: lgtm

#148 Make to gosec linter less obnoxious by disabling some checks
  .golangci.yaml
Labels: lgtm

#146 Extended declarative status reporting
  apis/core/v1alpha1/commonobjectset_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/manifests/v1alpha1/packagemanifest_types.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_clusterobjectsets.yaml
  config/crds/package-operator.run_clusterobjectslice.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/crds/package-operator.run_objectsets.yaml
  config/crds/package-operator.run_objectslice.yaml
  config/packages/test-stub/deployment.yaml.gotmpl
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsets.yaml
  config/static-deployment/1-package-operator.run_clusterobjectslice.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsets.yaml
  config/static-deployment/1-package-operator.run_objectslice.yaml
  docs/api-reference.md
  install.yaml
  integration/objectdeployment_test.go
  integration/package_test.go
  internal/controllers/controllers.go
  internal/controllers/controllers_test.go
  internal/controllers/mocks_test.go
  internal/controllers/objectdeployments/objectset_reconciler.go
  internal/controllers/objectsetphases/objectsetphase_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
  internal/controllers/objectsets/remotephase_reconciler.go
  internal/controllers/packages/object_deployment_status_reconciler.go
  internal/controllers/phase_reconciler.go
  internal/controllers/phase_reconciler_test.go
  internal/packages/packagecontent/conditionmap.go
  internal/packages/packagecontent/conditionmap_test.go
  internal/packages/packagecontent/totemplate.go
  internal/packages/packagedeploy/deployment_reconciler_test.go
  internal/probing/parse.go
  internal/probing/probe.go
Labels: lgtm, approved

#161 Make updatecmd_test.go a real unit test
  cmd/kubectl-package/command/command.go
  cmd/kubectl-package/command/updatecmd/testdata/manifest.lock.yaml
  cmd/kubectl-package/command/updatecmd/testdata/manifest.yaml
  cmd/kubectl-package/command/updatecmd/updatecmd.go
  cmd/kubectl-package/command/updatecmd/updatecmd_test.go
Labels: lgtm, approved

#162 Fix ClusterRole objects not included in PKO Package
  magefile.go
Labels: lgtm, approved

#165 Use the self-bootstrap-job to install PKO in dev and test
  magefile.go
Labels: lgtm, approved

#164 Use sha256 for hashing and clean finished job pods
  internal/controllers/objectdeployments/hash_reconciler.go
  internal/controllers/packages/adapter_package.go
  internal/controllers/packages/job_reconciler.go
  internal/packages/packagedeploy/deployment_reconciler.go
  internal/utils/hash.go
  internal/utils/hash_test.go
Labels: lgtm, approved

#166 Fix deadlock for namespace deletion
  internal/controllers/objectsets/remotephase_reconciler.go
  internal/controllers/objectsets/remotephase_reconciler_test.go
Labels: lgtm, approved

#155 Move image building and pushing functionality to DevKube
  go.mod
  go.sum
  magefile.go
Labels: lgtm, approved, needs-ok-to-test

#152 Add manifest.lock.yaml image and digest validation in build subcommand
  cmd/kubectl-package/command/buildcmd/build.go
  cmd/kubectl-package/command/buildcmd/build_validation_test.go
  cmd/kubectl-package/command/buildcmd/testdata/manifest.lock.yaml
Labels: lgtm, approved

#168 Repair package building
  go.mod
  go.sum
  go.work.sum
  magefile.go
Labels: lgtm, approved

#159 Update dependencies
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved

#171 Allow hypershift to be installed slower than PKO
  cmd/package-operator-manager/hypershift.go
  cmd/package-operator-manager/hypershift_test.go
  cmd/package-operator-manager/main.go
  integration/hypershift_test.go
  integration/testdata/hostedclusters.crd.yaml
  magefile.go
Labels: approved

#175 Increase bootstrap job timeout to 30min
  config/self-bootstrap-job.yaml.tpl
Labels: do-not-merge/hold

#176 Increase bootstrap job timeout to 30min
  hack/hive/deployment-template.yaml
Labels: lgtm, approved

#177 Do not unit test when linting
  magefile.go
Labels: lgtm

#172 Add safe sprig functions to template engine
  go.mod
  go.sum
  internal/packages/packageloader/transformfiles.go
  internal/packages/packageloader/transformfiles_funcs.go
  internal/packages/packageloader/transformfiles_funcs_test.go
Labels: lgtm, approved

#174 Let manager clean up all dangling pods on startup
  cmd/package-operator-manager/cleaner.go
  cmd/package-operator-manager/cleaner_test.go
  cmd/package-operator-manager/main.go
  go.mod
  go.sum
  go.work.sum
Labels: do-not-merge/hold

#156 Refactor commands
  cmd/cmdutil/error.go
  cmd/cmdutil/log.go
  cmd/cmdutil/validation.go
  cmd/kubectl-package/command/buildcmd/build.go
  cmd/kubectl-package/command/treecmd/tree.go
  cmd/kubectl-package/command/updatecmd/updatecmd.go
  cmd/kubectl-package/command/validatecmd/validatecmd.go
  cmd/kubectl-package/export/export.go
  cmd/kubectl-package/export/output_test.go
  cmd/kubectl-package/export/push_test.go
  internal/packages/packageexport/image_test.go
  internal/testutil/registry.go
Labels: lgtm

#179 Bump go.mod go version to indicate that go1.19 is minimum
  go.mod
Labels: lgtm, approved

#183 Add rob to OWNERS
  OWNERS
Labels: do-not-merge/invalid-owners-file

#184 Add eqrx to reviewers in OWNERS
  OWNERS
Labels: lgtm, approved

#181 Add command line arguments to kubectl-package tree to support config
  cmd/kubectl-package/command/treecmd/testdata/.config.yaml
  cmd/kubectl-package/command/treecmd/testdata/deployment.yaml.gotmpl
  cmd/kubectl-package/command/treecmd/testdata/manifest.yaml
  cmd/kubectl-package/command/treecmd/tree.go
  cmd/kubectl-package/command/treecmd/tree_test.go
Labels: lgtm, approved

#185 Update dependencies
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: lgtm, approved

#189 Add mark to OWNERS
  OWNERS
Labels: lgtm, approved

#188 Remote Phase Manager lacks ObjectSet permissions
  apis/core/v1alpha1/clusterobjectsetphase_types.go
  apis/core/v1alpha1/objectsetphase_types.go
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/20-rbac.yaml
  docs/api-reference.md
  install.yaml
  integration/hypershift_test.go
  integration/objectset_test.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/phase_reconciler.go
  internal/controllers/phase_reconciler_test.go
  internal/ownerhandling/annotation.go
  internal/ownerhandling/annotation_test.go
  internal/ownerhandling/common.go
  internal/ownerhandling/native.go
  internal/ownerhandling/native_test.go
  internal/testutil/ownerhandlingmocks/ownerstrategy_mock.go
Labels: lgtm, approved

#190 Add more logging and generation predicate for ObjectSets
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/phase_reconciler.go
Labels: lgtm, approved, ¯\_(ツ)_/¯

#191 Use server-side-apply
  internal/controllers/phase_reconciler.go
Labels: lgtm, approved

#186 Add resolved images to template engine context
  internal/packages/packagedeploy/deployer.go
  internal/packages/packagedeploy/deployer_test.go
  internal/packages/packageloader/transformfiles.go
Labels: lgtm, approved

#187 Let fieldsEqualProbe output status less convoluted
  internal/probing/probe.go
  internal/probing/probe_test.go
Labels: lgtm, approved

#194 Let dependabot manage indirect dependencies and always assign eqrx
  .github/dependabot.yml
Labels: lgtm, approved
