Repository package-operator/package-operator, pull requests merged in 2023-06, with the labels that each got.

#302 remove required probe in packageadmission module
  integration/kubectl-package/build_test.go
  integration/kubectl-package/testdata/packages/invalid/bad_manifest/manifest.yaml
  integration/kubectl-package/tree_test.go
  integration/kubectl-package/validate_test.go
  internal/packages/packageadmission/configuration_test.go
  internal/packages/packageadmission/manifest.go
  internal/packages/packageadmission/manifest_test.go
Labels: lgtm, approved

#317 Fix environment key
  config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl
  config/packages/package-operator/trusted-ca-bundle.ConfigMap.yaml.gotmpl
Labels: lgtm, approved

#316 add object duplicate validator
  internal/packages/errors.go
  internal/packages/packageloader/loader.go
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/validate.go
  internal/preflight/empty_namespace_no_default.go
Labels: lgtm, approved

#319 [MTSRE-1300] Fix data race when Packages are loaded in parallel
  internal/packages/packagecontent/content.go
  internal/packages/packagecontent/content_test.go
  internal/packages/packageimport/registry.go
  internal/packages/packageimport/registry_test.go
Labels: lgtm, approved

#305 Enable more Linters
  .golangci.yaml
  internal/cmd/build_test.go
  internal/cmd/update.go
  internal/controllers/controllers.go
  internal/controllers/objectdeployments/adapter_objectset.go
  internal/controllers/objectdeployments/adapter_test.go
  internal/controllers/phase_reconciler.go
  internal/packages/packagecontent/conditionmap.go
  internal/packages/packagecontent/totemplate.go
  internal/packages/packagedeploy/chunking.go
  internal/packages/packagedeploy/deployment_reconciler.go
  internal/packages/packageloader/validatefull.go
  internal/preflight/preflight.go
Labels: lgtm

#306 Let gh release create draft releases insted of just flag everything a…
  .github/workflows/release.yaml
Labels: lgtm

#321 Fix linting violation that got through
  go.work.sum
  internal/cli/printer.go
Labels: lgtm, approved

#326 Handle API status error with invalid reason string
  internal/preflight/dryrun.go
  internal/preflight/dryrun_test.go
Labels: lgtm, approved

#325 Mtsre 1253 expose environment info
  cmd/package-operator-manager/components/objecttemplate.go
  cmd/package-operator-manager/components/package.go
  cmd/package-operator-manager/components/setups.go
  go.work.sum
  integration/package-operator/objecttemplate_test.go
  internal/controllers/objecttemplate/objecttemplate_controller.go
  internal/controllers/objecttemplate/template_reconciler.go
  internal/controllers/objecttemplate/template_transformer.go
Labels: lgtm, approved

#331 add pbabic to OWNERS
  OWNERS
Labels: lgtm, approved, needs-ok-to-test

#330 delete unused Containerfile
  config/images/package.Containerfile
  magefile.go
Labels: lgtm, approved, ok-to-test
