Repository package-operator/package-operator, pull requests merged in 2023-03, with the labels that each got.

#207 Add Let's Encrypt root certificate to remote-phase-manager docker image
  config/images/remote-phase-manager.Containerfile
Labels: lgtm, approved

#209 Run codeql gh action only when pushed to main
  .github/workflows/codeql-analysis.yml
Labels: lgtm, approved

#218 Fix root CAs not included
  config/images/remote-phase-manager.Containerfile
Labels: lgtm, approved

#219 Fix root CAs not included
  config/images/remote-phase-manager.Containerfile
Labels: lgtm, approved

#220 Improve go dependency update management
  .github/dependabot.yml
  .gitignore
  go.work.sum
Labels: lgtm, ¯\_(ツ)_/¯

#222 Use custom workflow for go updates
  .github/dependabot.yml
  .github/workflows/update.yaml
  .gitignore
  go.work.sum
Labels: lgtm, approved

#170 Object Template Controller
  apis/core/v1alpha1/clusterobjecttemplate_types.go
  apis/core/v1alpha1/commonobjecttemplate_types.go
  apis/core/v1alpha1/objecttemplate_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  cmd/kubectl-package/command/treecmd/tree.go
  cmd/package-operator-manager/hypershift_test.go
  cmd/package-operator-manager/main.go
  config/crds/package-operator.run_clusterobjecttemplates.yaml
  config/crds/package-operator.run_objecttemplates.yaml
  config/static-deployment/1-package-operator.run_clusterobjecttemplates.yaml
  config/static-deployment/1-package-operator.run_objecttemplates.yaml
  docs/api-reference.md
  install.yaml
  integration/objecttemplate_test.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objecttemplate/objecttemplate_adapter.go
  internal/controllers/objecttemplate/objecttemplate_controller.go
  internal/controllers/objecttemplate/objecttemplate_controller_test.go
  internal/controllers/objecttemplate/template_transformer.go
  internal/controllers/objecttemplate/test_files/clusterpackage_template_to_json.yaml
  internal/controllers/objecttemplate/test_files/package_template_by_key.yaml
  internal/controllers/objecttemplate/test_files/package_template_to_json.yaml
  internal/controllers/phase_reconciler.go
  internal/packages/packagedeploy/deployer.go
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/package_files_template_transformer.go
  internal/packages/packageloader/package_transformer.go
  internal/packages/packageloader/validatefull.go
  internal/preflight/apis_exist.go
  internal/preflight/empty_namespace_no_default.go
  internal/preflight/namespace_escalation_protection.go
  internal/preflight/preflight.go
  internal/testutil/dynamiccachemocks/dynamiccache_mock.go
  internal/testutil/restmappermock/restmapper_mock.go
  internal/transform/transformfiles_funcs.go
  internal/transform/transformfiles_funcs_test.go
  magefile.go
Labels: lgtm, approved, tide/merge-method-squash

#231 Remove controller-runtime as dependency of apis
  apis/core/v1alpha1/clusterobjectdeployment_types.go
  apis/core/v1alpha1/clusterobjectset_types.go
  apis/core/v1alpha1/clusterobjectsetphase_types.go
  apis/core/v1alpha1/clusterobjectslices_types.go
  apis/core/v1alpha1/clusterobjecttemplate_types.go
  apis/core/v1alpha1/clusterpackage_types.go
  apis/core/v1alpha1/groupversion_info.go
  apis/core/v1alpha1/objectdeployment_types.go
  apis/core/v1alpha1/objectset_types.go
  apis/core/v1alpha1/objectsetphase_types.go
  apis/core/v1alpha1/objectslices_types.go
  apis/core/v1alpha1/objecttemplate_types.go
  apis/core/v1alpha1/package_types.go
  apis/go.mod
  apis/go.sum
  apis/manifests/v1alpha1/groupversion_info.go
  apis/manifests/v1alpha1/packagemanifest_types.go
  apis/manifests/v1alpha1/packagemanifestlock_types.go
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved

#233 Update readme
  DCO
  README.md
Labels: lgtm, approved

#230 Extend API to mark ObjectTemplate sources as optional
  apis/core/v1alpha1/commonobjecttemplate_types.go
  config/crds/package-operator.run_clusterobjecttemplates.yaml
  config/crds/package-operator.run_objecttemplates.yaml
  config/static-deployment/1-package-operator.run_clusterobjecttemplates.yaml
  config/static-deployment/1-package-operator.run_objecttemplates.yaml
  docs/api-reference.md
  install.yaml
  integration/objecttemplate_test.go
  internal/controllers/hostedclusters/hypershift/v1beta1/zz_generated.deepcopy.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objecttemplate/errors.go
  internal/controllers/objecttemplate/errors_test.go
  internal/controllers/objecttemplate/objecttemplate_adapter.go
  internal/controllers/objecttemplate/objecttemplate_controller.go
  internal/controllers/objecttemplate/objecttemplate_controller_test.go
  internal/controllers/objecttemplate/template_reconciler.go
  internal/controllers/objecttemplate/template_reconciler_test.go
  internal/controllers/objecttemplate/template_transformer.go
  internal/controllers/objecttemplate/test_files/clusterpackage_template_to_json.yaml
  internal/controllers/objecttemplate/testdata/package_template_by_key.yaml
  internal/controllers/objecttemplate/testdata/package_template_to_json.yaml
  internal/controllers/phase_reconciler.go
  internal/preflight/apis_exist.go
  internal/preflight/empty_namespace_no_default.go
  internal/preflight/namespace_escalation_protection.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
Labels: lgtm, approved

#235 Update dependencies
  go.mod
  go.sum
  go.work.sum
Labels: lgtm, approved

#238 [MTSRE-962] feat: allow specification of externally declared for status probing
  apis/core/v1alpha1/clusterobjectsetphase_types.go
  apis/core/v1alpha1/commonobjectset_types.go
  apis/core/v1alpha1/objectsetphase_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/manifests/v1alpha1/packagemanifest_types.go
  cmd/kubectl-package/command/treecmd/testdata/external-deployment.yaml.gotmpl
  cmd/kubectl-package/command/treecmd/tree.go
  cmd/kubectl-package/command/treecmd/tree_test.go
  cmd/package-operator-manager/main.go
  cmd/remote-phase-manager/main.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_clusterobjectsets.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/crds/package-operator.run_objectsets.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsets.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsets.yaml
  docs/api-reference.md
  install.yaml
  integration/objectdeployment_test.go
  internal/controllers/controllers.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/objecttemplate/template_reconciler.go
  internal/controllers/phase_reconciler.go
  internal/controllers/phase_reconciler_test.go
  internal/packages/packagecontent/totemplate.go
Labels: lgtm, approved, ok-to-test

#240 enforce JSONPath notation
  apis/core/v1alpha1/commonobjecttemplate_types.go
  config/crds/package-operator.run_clusterobjecttemplates.yaml
  config/crds/package-operator.run_objecttemplates.yaml
  config/static-deployment/1-package-operator.run_clusterobjecttemplates.yaml
  config/static-deployment/1-package-operator.run_objecttemplates.yaml
  docs/api-reference.md
  install.yaml
  integration/objecttemplate_test.go
  internal/controllers/objecttemplate/errors.go
  internal/controllers/objecttemplate/template_reconciler.go
  internal/controllers/objecttemplate/template_reconciler_test.go
Labels: lgtm, approved, tide/merge-method-squash

#245 Fix ObjectTemplate controller wrongly triggered
  internal/controllers/objecttemplate/objecttemplate_controller.go
Labels: lgtm, approved
