Repository package-operator/package-operator, pull requests merged in 2023-10, with the labels that each got.

#533 MTSRE-1520: Enable PKO sub-component affinity and toleration
  cmd/package-operator-manager/components/hostedcluster.go
  cmd/package-operator-manager/components/options.go
  config/examples/packages/test-stub.yaml
  config/packages/package-operator/.test-fixtures/affinity-tolerations-resources/package-operator-manager.Deployment.yaml
  config/packages/package-operator/package-operator-manager.Deployment.yaml.gotmpl
  config/packages/remote-phase/manifest.yaml.tpl
  config/packages/remote-phase/package-operator-remote-phase-manager.Deployment.yaml.gotmpl
  internal/controllers/hostedclusters/hostedcluster_controller.go
  internal/controllers/hostedclusters/hostedcluster_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#524 [MTSRE-1346] Validate multi component images in cli builder
  internal/packages/filenames.go
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/backend/components/banana/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/backend/components/banana/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/backend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/frontend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/components/frontend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/nested-components/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/not-dns1123/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/not-dns1123/components/_backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/not-dns1123/components/_backend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/not-dns1123/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/components/backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/components/backend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/components/frontend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/components/frontend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled/valid/manifest.yaml
  internal/packages/packagecontent/topackage.go
  internal/packages/packagecontent/topackage_multicomponent_test.go
  internal/packages/violation.go
Labels: lgtm, approved

#550 Fix loader_test with config
  internal/packages/packagecontent/topackage_multicomponent_test.go
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/testdata/Containerfile
  internal/packages/packageloader/testdata/deployment.yml.gotmpl
  internal/packages/packageloader/testdata/manifest.yaml
Labels: lgtm, approved

#554 Fix multicomponent loading test because file odering is not stable when loading packages
  internal/packages/packagecontent/topackage_multicomponent_test.go
Labels: lgtm, approved

#553 MTSRE-1571: Fix YAML document split breaks PEM certs
  internal/packages/packagecontent/topackage.go
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/testdata/deployment.yml.gotmpl
Labels: lgtm, approved, jira/valid-reference

#551 MTSRE-1520: Fix typo for remote-phase tolerations
  cmd/package-operator-manager/components/options_test.go
  internal/controllers/hostedclusters/hostedcluster_controller.go
  internal/controllers/hostedclusters/hostedcluster_controller_test.go
Labels: approved, jira/valid-reference

#555 Add more details to YAML parser error
  internal/packages/packagecontent/topackage.go
  internal/packages/violation.go
  internal/packages/violation_test.go
Labels: lgtm

#549 Remove workarounds for go v1.19
  go.mod
  go.sum
  integration/kubectl-package/kubectl-package_suite_test.go
  magefiles/config.go
  magefiles/ns_test_mg.go
Labels: lgtm, approved

#570 Improve our extensive assorted collection of linters 🎩
  .golangci.yaml
  internal/packages/packagecontent/tofiles.go
Labels: lgtm, approved

#568 Correctly handle config fields in multi component packages
  internal/cmd/tree.go
  internal/cmd/tree_test.go
  internal/packages/packagecontent/splitfiles.go
  internal/packages/packagecontent/splitfiles_test.go
  internal/packages/packagecontent/topackage.go
  internal/packages/packagecontent/topackage_multicomponent_test.go
  internal/packages/packagecontent/topackage_test.go
  internal/packages/packageloader/loader.go
  internal/packages/packageloader/loader_test.go
  internal/testutil/testdata/multi-with-config/backend-package.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/components/backend/deployment.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/components/backend/manifest.yaml
  internal/testutil/testdata/multi-with-config/components/backend/service.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/components/frontend/configmap.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/components/frontend/deployment.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/components/frontend/manifest.yaml
  internal/testutil/testdata/multi-with-config/components/frontend/service.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/frontend-package.yaml.gotmpl
  internal/testutil/testdata/multi-with-config/manifest.yaml
  internal/testutil/testdata/simple-with-config/configmap.yaml.gotmpl
  internal/testutil/testdata/simple-with-config/deployment.yaml
  internal/testutil/testdata/simple-with-config/manifest.yaml
  internal/testutil/testdata/simple-with-config/service.yaml
Labels: approved

#545 Make probing a public package.
  .github/workflows/release.yaml
  go.mod
  go.work
  internal/controllers/objectsetphases/objectsetphase_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
  internal/controllers/phase_reconciler.go
  internal/probing/parse.go
  internal/probing/parse_test.go
  internal/probing/probe.go
  internal/probing/probe_test.go
  internal/probing/selectors.go
  internal/testutil/controllersmocks/phasereconciler_mock.go
  pkg/README.md
  pkg/go.mod
  pkg/go.sum
  pkg/probing/cel.go
  pkg/probing/cel_test.go
  pkg/probing/condition.go
  pkg/probing/condition_test.go
  pkg/probing/doc.go
  pkg/probing/fieldsequal.go
  pkg/probing/fieldsequal_test.go
  pkg/probing/observedgeneration.go
  pkg/probing/observedgeneration_test.go
  pkg/probing/probe.go
  pkg/probing/probe_test.go
  pkg/probing/selectors.go
  pkg/probing/selectors_test.go
Labels: lgtm, approved

#572 Fix kubectl-package tree panic with packages with config, no tests and no required props
  integration/kubectl-package/fixtures_test.go
  integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/README.md
  integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/deployment.yaml.gotmpl
  integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/external-deployment.yaml.gotmpl
  integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/manifest.yaml
  integration/kubectl-package/testdata/packages/valid/with_config_no_tests_no_required_properties/namespace.template.yaml.gotmpl
  integration/kubectl-package/tree_test.go
  internal/cmd/tree.go
Labels: approved

#588 Run linter in submodules
  .golangci.yaml
  apis/manifests/v1alpha1/packagemanifest_types.go
  docs/api-reference.md
  magefiles/ns_test_mg.go
  pkg/probing/cel.go
  pkg/probing/selectors_test.go
Labels: lgtm, approved
