Repository package-operator/package-operator, pull requests merged in 2023-09, with the labels that each got.

#446 Revert back to creating CRDs before bootstrap instead of applying the…
  cmd/package-operator-manager/bootstrap/init.go
  cmd/package-operator-manager/bootstrap/init_test.go
Labels: lgtm

#442 split magefile into a package in ./magefiles and drop unused functions
  .pre-commit-config.yaml
  .vscode/settings.json
  mage
  magefile.go
  magefiles/config.go
  magefiles/helper.go
  magefiles/locations.go
  magefiles/ns_build.go
  magefiles/ns_dependency.go
  magefiles/ns_dev.go
  magefiles/ns_generate.go
  magefiles/ns_test_mg.go
  magefiles/root.go
Labels: lgtm, approved

#414 Depsideps
  .golangci.yaml
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/go.mod
  apis/manifests/v1alpha1/zz_generated.deepcopy.go
  cmd/package-operator-manager/components/components.go
  cmd/package-operator-webhook/main.go
  cmd/remote-phase-manager/main.go
  config/crds/package-operator.run_clusterobjectdeployments.yaml
  config/crds/package-operator.run_clusterobjectsetphases.yaml
  config/crds/package-operator.run_clusterobjectsets.yaml
  config/crds/package-operator.run_clusterobjectslices.yaml
  config/crds/package-operator.run_clusterobjecttemplates.yaml
  config/crds/package-operator.run_clusterpackages.yaml
  config/crds/package-operator.run_objectdeployments.yaml
  config/crds/package-operator.run_objectsetphases.yaml
  config/crds/package-operator.run_objectsets.yaml
  config/crds/package-operator.run_objectslices.yaml
  config/crds/package-operator.run_objecttemplates.yaml
  config/crds/package-operator.run_packages.yaml
  config/static-deployment/1-package-operator.run_clusterobjectdeployments.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsetphases.yaml
  config/static-deployment/1-package-operator.run_clusterobjectsets.yaml
  config/static-deployment/1-package-operator.run_clusterobjectslices.yaml
  config/static-deployment/1-package-operator.run_clusterobjecttemplates.yaml
  config/static-deployment/1-package-operator.run_clusterpackages.yaml
  config/static-deployment/1-package-operator.run_objectdeployments.yaml
  config/static-deployment/1-package-operator.run_objectsetphases.yaml
  config/static-deployment/1-package-operator.run_objectsets.yaml
  config/static-deployment/1-package-operator.run_objectslices.yaml
  config/static-deployment/1-package-operator.run_objecttemplates.yaml
  config/static-deployment/1-package-operator.run_packages.yaml
  go.mod
  go.sum
  install.yaml
  internal/packages/packagedeploy/deployer_test.go
  internal/utils/imageurl_test.go
  magefiles/config.go
Labels: lgtm, approved

#456 Refactor HyperShift integration tests for re-run
  config/examples/packages/test-stub.yaml
  integration/package-operator/hypershift_test.go
Labels: lgtm, approved

#457 [MTSRE-1426] Fix bootstrap controller shutdown when context is cancelled
  internal/environment/environment.go
Labels: lgtm, approved

#332 Mtsre 1036 duplicate object check number 2
  go.mod
  go.sum
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/objectsets/objectset_controller_test.go
  internal/controllers/objectsets/objectsetphases_reconciler.go
  internal/controllers/objectsets/objectsetphases_reconciler_test.go
  internal/packages/packageloader/validate.go
  internal/preflight/object_duplicate.go
  internal/preflight/object_duplicate_test.go
  internal/preflight/preflight.go
  internal/preflight/preflight_test.go
Labels: lgtm, approved

#481 Change PackageManifestSpec.Component to correct type
  apis/core/v1alpha1/commonpackage_types.go
  apis/manifests/v1alpha1/packagemanifest_types.go
  apis/manifests/v1alpha1/zz_generated.deepcopy.go
  config/crds/package-operator.run_clusterpackages.yaml
  config/crds/package-operator.run_packages.yaml
  config/static-deployment/1-package-operator.run_clusterpackages.yaml
  config/static-deployment/1-package-operator.run_packages.yaml
  docs/api-reference.md
  install.yaml
Labels: lgtm, approved

#495 [MTSRE-1471] Fix race condition in objectset handover integration tes…
  integration/package-operator/objectset_test.go
Labels: lgtm, approved

#482 Reduce usage of direct dependencies
  cmd/package-operator-manager/bootstrap/proxy/proxy_test.go
  go.mod
  go.sum
  internal/cmd/validate_test.go
  internal/controllers/objectdeployments/archive_reconciler_test.go
  internal/packages/packagedeploy/deployer.go
  internal/packages/packagedeploy/deployer_test.go
  internal/utils/imageurl.go
  internal/utils/imageurl_test.go
  magefiles/config.go
Labels: lgtm, approved

#504 MTSRE-1504: Add include template function
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/package_files_template_transformer.go
  internal/packages/packageloader/testdata/_helpers.gotmpl
  internal/packages/packageloader/testdata/deployment.yml.gotmpl
  internal/transform/transformfiles_funcs.go
  internal/transform/transformfiles_funcs_test.go
Labels: lgtm, approved, jira/valid-reference

#505 Add file access from template engine
  go.mod
  go.sum
  internal/packages/packagecontent/topackage.go
  internal/packages/packageloader/loader_test.go
  internal/packages/packageloader/package_files_template_transformer.go
  internal/packages/packageloader/testdata/_stuff.txt
  internal/packages/packageloader/testdata/deployment.yml.gotmpl
  internal/transform/file_funcs.go
  internal/transform/file_funcs_test.go
  internal/transform/transformfiles_funcs.go
  internal/transform/transformfiles_funcs_test.go
Labels: lgtm, approved

#509 Don't report reconciliation of objectsetphases twice in logs.
  internal/controllers/objectsetphases/objectsetphase_controller.go
Labels: lgtm, approved

#503 Let loader support multi component images
  apis/manifests/v1alpha1/packagemanifest_types.go
  apis/manifests/v1alpha1/zz_generated.deepcopy.go
  cmd/kubectl-package/treecmd/tree.go
  docs/api-reference.md
  internal/adapters/package.go
  internal/adapters/package_test.go
  internal/cmd/build.go
  internal/cmd/build_test.go
  internal/cmd/options.go
  internal/cmd/tree.go
  internal/packages/packagecontent/testdata/base/Containerfile
  internal/packages/packagecontent/testdata/base/manifest.yaml
  internal/packages/packagecontent/testdata/base/some-statefulset.yaml
  internal/packages/packagecontent/testdata/multi-component/components-disabled/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-disabled/components/backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-disabled/components/frontend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-disabled/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-invalid/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-invalid/components/_backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-invalid/components/_backend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-invalid/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/ConfigMap.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/components/backend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/components/backend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/components/frontend/Deployment.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/components/frontend/manifest.yaml
  internal/packages/packagecontent/testdata/multi-component/components-enabled-valid/manifest.yaml
  internal/packages/packagecontent/topackage.go
  internal/packages/packagecontent/topackage_multicomponent_test.go
  internal/packages/packagecontent/topackage_test.go
  internal/packages/packagedeploy/deployer.go
  internal/packages/packageloader/loader.go
  internal/packages/violation.go
Labels: lgtm, approved

#498 [MTSRE-1471] Fix orphaning of objects owned by (Cluster)ObjectSets and their phases
  cmd/remote-phase-manager/main.go
  internal/controllers/objectsetphases/objectsetphase_controller.go
  internal/controllers/objectsetphases/objectsetphase_reconciler.go
  internal/controllers/objectsets/objectset_controller.go
  internal/controllers/objectsets/remotephase_reconciler.go
  internal/controllers/objectsets/remotephase_reconciler_test.go
  internal/controllers/phase_reconciler.go
  internal/controllers/phase_reconciler_test.go
  internal/testutil/ownerhandlingmocks/ownerstrategy_mock.go
Labels: lgtm, approved

#508 Set eqrx as code owner of go, github actions and dependabot
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: lgtm, approved
